package config

import (
	"bufio"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// parityGoldenPath / parityAllowlistPath are relative to this package dir
// (api/v1beta1/kubemqcluster/config → four levels up to the k8s module root).
const (
	parityGoldenPath    = "../../../../parity/server_env_keys.txt"
	parityAllowlistPath = "../../../../parity/configdata_allowlist.txt"
)

// TestConfigParity_ServerKeysEmittedOrAllowlisted is the ADD-014 env-emission parity guard.
// It fails the build when the kubemq-server honors an env-var key that neither a CRD
// SetConfig emits nor the allowlist intentionally excludes to spec.configData — i.e. the
// exact drift that let the MQTT/A2A/GCP field gaps accumulate. serverKeys come from the
// committed golden (regenerated by `task parity:regen`); emitted keys are extracted
// statically from every SetConfig in this package (no runtime fixture → no enable-polarity
// false reds).
func TestConfigParity_ServerKeysEmittedOrAllowlisted(t *testing.T) {
	server := readKeyFile(t, parityGoldenPath)
	allowExact, allowPrefix := readAllowlist(t, parityAllowlistPath)
	emitted := extractEmittedKeys(t)

	// 1) completeness: every server key is emitted OR allowlisted.
	var missing []string
	for k := range server {
		if emitted[k] || allowExact[k] || matchesPrefix(k, allowPrefix) {
			continue
		}
		missing = append(missing, k)
	}
	sort.Strings(missing)
	require.Empty(t, missing, "config-parity gap: the server honors these env keys but no CRD "+
		"SetConfig emits them and they are not allowlisted — add a typed CRD field or allowlist "+
		"them to spec.configData (parity/configdata_allowlist.txt):\n%s", strings.Join(missing, "\n"))

	// 2) no-stale: every exact allowlist entry must be a real server key (else the allowlist rots).
	var stale []string
	for k := range allowExact {
		if !server[k] {
			stale = append(stale, k)
		}
	}
	sort.Strings(stale)
	require.Empty(t, stale, "stale allowlist entries — these are not (any longer) server keys, remove them:\n%s",
		strings.Join(stale, "\n"))

	// 3) no-stale prefixes: every allowlist prefix must cover at least one server key.
	var deadPrefix []string
	for p := range allowPrefix {
		hit := false
		for k := range server {
			if strings.HasPrefix(k, p) {
				hit = true
				break
			}
		}
		if !hit {
			deadPrefix = append(deadPrefix, p+"*")
		}
	}
	sort.Strings(deadPrefix)
	require.Empty(t, deadPrefix, "allowlist prefixes matching no server key — remove them:\n%s",
		strings.Join(deadPrefix, "\n"))

	// 4) no-overlap: an exact allowlist entry that is now emitted should be a typed field, not
	// allowlisted (otherwise API_BIND_ADDRESS-style double-listing red-builds the intent).
	var overlap []string
	for k := range allowExact {
		if emitted[k] {
			overlap = append(overlap, k)
		}
	}
	sort.Strings(overlap)
	require.Empty(t, overlap, "allowlisted keys that ARE emitted — remove them from the allowlist "+
		"(they satisfy parity directly):\n%s", strings.Join(overlap, "\n"))
}

func readKeyFile(t *testing.T, path string) map[string]bool {
	t.Helper()
	f, err := os.Open(path)
	require.NoError(t, err, "open %s", path)
	defer f.Close()
	keys := map[string]bool{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		keys[line] = true
	}
	require.NoError(t, sc.Err())
	require.NotEmpty(t, keys, "%s is empty", path)
	return keys
}

// readAllowlist parses configdata_allowlist.txt. Each non-comment line is `KEY  # reason` or
// `PREFIX_*  # reason`. A trailing `*` makes it a prefix rule.
func readAllowlist(t *testing.T, path string) (exact map[string]bool, prefix map[string]bool) {
	t.Helper()
	f, err := os.Open(path)
	require.NoError(t, err, "open %s", path)
	defer f.Close()
	exact, prefix = map[string]bool{}, map[string]bool{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if i := strings.Index(line, "#"); i >= 0 {
			line = line[:i]
		}
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if strings.HasSuffix(line, "*") {
			prefix[strings.TrimSuffix(line, "*")] = true
		} else {
			exact[line] = true
		}
	}
	require.NoError(t, sc.Err())
	return exact, prefix
}

func matchesPrefix(key string, prefix map[string]bool) bool {
	for p := range prefix {
		if strings.HasPrefix(key, p) {
			return true
		}
	}
	return false
}

// extractEmittedKeys statically walks every non-test .go file in this package and collects
// the string-literal env-var names passed to the ConfigMap/Secret setters. Argument index by
// setter: SetConfigMapStringValues/SetSecretStringValues/SetSecretDataValues take (name, KEY,
// value) → arg[1]; SetStringVariable/SetDataVariable take (KEY, value) → arg[0].
func extractEmittedKeys(t *testing.T) map[string]bool {
	t.Helper()
	entries, err := os.ReadDir(".")
	require.NoError(t, err)
	keyArg := map[string]int{
		"SetConfigMapStringValues": 1,
		"SetSecretStringValues":    1,
		"SetSecretDataValues":      1,
		"SetStringVariable":        0,
		"SetDataVariable":          0,
	}
	emitted := map[string]bool{}
	// A few keys are emitted as `prefix + "_SUFFIX"` (the shared CorsConfig.setConfig writes
	// prefix+"_ALLOW_ORIGINS" etc., with prefix passed as a literal at each call site, e.g.
	// "CONNECTORS_HTTP_CORS"). Collect the prefixes and the concatenation suffixes separately,
	// then cross-product. Spurious combos are harmless (they only satisfy ⊆, never cause a miss).
	var dynPrefixes, dynSuffixes []string
	fset := token.NewFileSet()
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, e.Name(), nil, 0)
		require.NoError(t, err, "parse %s", e.Name())
		ast.Inspect(f, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			// Prefix literals passed to the shared cors emitter `x.setConfig(config, "PREFIX")`.
			if sel.Sel.Name == "setConfig" && len(call.Args) >= 2 {
				if bl, ok := call.Args[1].(*ast.BasicLit); ok && bl.Kind == token.STRING {
					dynPrefixes = append(dynPrefixes, strings.Trim(bl.Value, "`\""))
				}
			}
			idx, ok := keyArg[sel.Sel.Name]
			if !ok || idx >= len(call.Args) {
				return true
			}
			switch a := call.Args[idx].(type) {
			case *ast.BasicLit:
				if a.Kind == token.STRING {
					emitted[strings.Trim(a.Value, "`\"")] = true
				}
			case *ast.BinaryExpr: // prefix + "_SUFFIX"
				if bl, ok := a.Y.(*ast.BasicLit); ok && bl.Kind == token.STRING {
					dynSuffixes = append(dynSuffixes, strings.Trim(bl.Value, "`\""))
				}
			}
			return true
		})
	}
	for _, p := range dynPrefixes {
		for _, s := range dynSuffixes {
			emitted[p+s] = true
		}
	}
	require.NotEmpty(t, emitted, "no emitted keys extracted — setter names changed?")
	return emitted
}
